version: "2"
services:
  app:
    container_name: flay
    build:
      context: ../
      dockerfile: deployments/app/Dockerfile
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
  db:
    build: "./db"