version: "2"
services:
  app:
    container_name: flay
    build:
      context: ./
      dockerfile: app/Dockerfile
    volumes:
      - "./app:/app"
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
  db:
    image: mongo:4.0.0